Models/ErrorViewModel.cs
namespace WeatherApi_Core.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GetWeatherData.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace WeatherApi_Core.Models
{
    public class GetWeatherData
    {
        public LocationData Location { get; set; }
        public CurrentWeatherData Current { get; set; }
        [Required]
        [Display(Name = "City Name")]
        public string City { get; set; }

    }
    public class LocationData
    {

        public string Name { get; set; }
        [Display(Name = "Region")]
        public string Region { get; set; }
        [Display(Name = "Country")]
        public string Country { get; set; }
        [Display(Name = "Lattitude")]
        public double Lat { get; set; }
        [Display(Name = "Longitude")]
        public double Lon { get; set; }
        [Display(Name = "TzId")]
        [JsonPropertyName("tz_id")]
        public string TzId { get; set; }
        public int LocaltimeEpoch { get; set; }
        [Display(Name = "Local Time")]
        public string Localtime { get; set; }
    }

    public class CurrentWeatherData
    {
        [Display(Name = "Temperature In Celsius")]
        [JsonPropertyName("temp_c")]
        public double TempC { get; set; }
        [Display(Name = "Temperature In Fahrenheit")]
        [JsonPropertyName("temp_f")]
        public double TempF { get; set; }
        [Display(Name = "Last Updated On")]
        [JsonPropertyName("last_updated")]
        public string LastUpdateOn { get; set; }
        [Display(Name = "Wind Speed(KM/H)")]
        [JsonPropertyName("wind_kph")]
        public double Wind { get; set; }
        [Display(Name = "Humidity")]
        [JsonPropertyName("humidity")]
        public double Humidity { get; set; }
        [Display(Name = "Cloud")]
        [JsonPropertyName("cloud")]
        public double Cloud { get; set; }
        public Condition Condition { get; set; }
    }

    public class Condition
    {
        [Display(Name = "Current Condition")]
        public string Text { get; set; }
        public string Icon { get; set; }
        public int Code { get; set; }
    }

}

Models/IWeatherApiConfiguration.cs
namespace WeatherApi_Core.Models
{
    public interface IWeatherApiConfiguration
    {
        string ApiKey { get; set; }
    }
}

Models/WeatherApiConfiguration.cs
namespace WeatherApi_Core.Models
{
    public class WeatherApiConfiguration : IWeatherApiConfiguration
    {
        public string ApiKey { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WeatherApi_Core.Models;

namespace WeatherApi_Core.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherApi_Core.Models;
using WeatherApi_Core.WeatherServices;

namespace WeatherApi_Core.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IGetWeatherService _weatherServices;

        public WeatherController(IGetWeatherService getWeatherService)
        {
            _weatherServices = getWeatherService;
        }


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetWeather(GetWeatherData getWeatherData)
        {
            if (getWeatherData.City != null)
            {
                var weatherData = await _weatherServices.GetCurrentWeather(getWeatherData.City);
                if (weatherData != null)
                {
                    GetWeatherData GetWeatherData = new GetWeatherData();

                    GetWeatherData.City = weatherData.Location.Name;

                    GetWeatherData.Location = weatherData.Location;

                    GetWeatherData.Current = weatherData.Current;

                    GetWeatherData.Current.Condition = weatherData.Current.Condition;

                    Console.WriteLine("response : " + weatherData);
                    ViewBag.mssg = "SHOWING WEATHER UPDATE FOR : " + getWeatherData.City;
                    return View(GetWeatherData);
                }
                return View("Error");
            }
            else 
            {
                ModelState.AddModelError("CustomError", "Required Feild");
                return View("Index");
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherApi_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherApi_Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeatherApi_Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Get Current Weather</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WeatherApi_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Weather/GetWeather.cshtml
@model WeatherApi_Core.Models.GetWeatherData

@{
    ViewData["Title"] = "GetWeather";
}

<h1>GetWeather</h1>
@ViewBag.mssg


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Lat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Lon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Localtime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.TzId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.TempC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.TempF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.Condition.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.LastUpdateOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.Wind)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.Humidity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Current.Cloud)
            </th>
            <th>
                @Html.Raw("Weather Status")
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(Model => Model.City)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.Region)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.Country)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.Lat)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.Lon)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.Localtime)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Location.TzId)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.TempC)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.TempF)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.Condition.Text)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.LastUpdateOn)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.Wind)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.Humidity)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.Current.Cloud)
            </td>
            <td>
                <img src ="@Model.Current.Condition.Icon" alt="Weather Icon" />
            </td>
        </tr>
    </tbody>
</table>

Views/Weather/Index.cshtml
@model GetWeatherData

@using (Html.BeginForm("GetWeather", "Weather"))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     <div class="row form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
     <div class="col-10 input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
     </div>
     </div>
         <div class="row form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit">Submit City</button>
                    </div>
         </div>
}